databases:
  - name: hvnpod-db
    plan: free
    databaseName: hvnpod
    user: hvnpod

services:
  - type: web
    plan: free
    name: hvnpod
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hvnpod-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
